language: node_js
node_js:
- '0.12'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GHREPO=github.com/jupyter/jupyter-js-input-area.git
  - secure: OD3YDtaN9x0mprY3lMS/6ascFTTavayxxRYzpTvapZCrVJ9dpj90K3KhcfUlG4ZWncJvgpzAh69qBcBOTbUx9Wq+N6SbAoo8k8sOPreRRYAqJz7tPV6Ixhmi/5psdeFT4EomiBjytDF8Gsm9m34WnI4XDpGHL5uBQFr35mxJC7/o4Aji0sc7DCP5YyxyHgTWD40uL6KQZy65EKPXDk09CMx5+/xAw8IF6oQCJXVvGK99yBCniXaT83nUbaHH93MVjNJjscdps6havQ7YlBvkw+2SbZx+APpKQuyoHEfV8unaXEQ8M3Gzzng57FlrjsVxScsbEsnPV81a9Kbk8hIoNUg1heEmvWqGUABIYd1QVlckpfpd033RHDqG1On7sk5elu3Bmm3AC8rf0cGNYZhTkwawBKFUrQ/0D321ndpEQpx7uj7ZrQxiPwZyUpdcyPoHPaJosxiUcK7wnS1akwFAVW2cdv4kKdrdi6OQcn/zjIsEMNCozj2n2B0HMyDUekB/P4AHIr4aOqTB5GIgQgerKT+xwR1DVSuQb61v798o0ndIbWxi95OoxZzWLnWETDgU9/PI0F27bG5ms8BY3MrS42oiuj/s0Sdao6weMTCtZ72r45qnwupqA68WM5Lv17ESgbHUypbn0iZ4bmNmXs4yPYqD70sD6UJAkv6kEjKIjKQ=
install:
- bash scripts/travis_install.sh
script:
- bash scripts/travis_script.sh
after_success:
- bash scripts/travis_after_success.sh
